name: ci

on:
  push:
    paths: 
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Shorten Commit id to 6 chars
        shell : bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> ${GITHUB_ENV}

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: aumthakkar/py-app-2:${{ env.COMMIT_ID }}
   
    outputs: 
      commit_id: ${{ env.COMMIT_ID }} 


  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - name: Clone github repo
        uses: actions/checkout@v3

      - name: Update argocd monitored charts/py-app values file 
        shell: bash
        run: |
          echo ${{ needs.ci.outputs.commit_id }}
          pip install yq 
          yq -Yi ('.image.tag = "${{ needs.ci.outputs.commit_id }}"') charts/py-app/values.yaml

      - name: Commit changes to github  
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Updates charts/python-app/values.yaml with latest commit: ${{needs.ci.outputs.commit_id}}'

      - name: Install Argocd # To run the argocd app sync <application> argocd CLI 
        shell: bash
        run: |
          curl -ksSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/argocd

      - name: Argocd app sync
        shell: bash
        run:
          argocd login argocd-server.argocd \
          --insecure \
          --grpc-web \
          --username admin \
          --password ${{ secrets.ARGOCD_PASSWORD }}
          
          argocd app sync py-app
          



        

